### ISSUE TITLE
sync error 

### ISSUE THREAD

**Issue by zacchaeusliang** [linaro-swg/optee_android_manifest#70] opened 2020-05-30 14:23 UTC
Hello i have an error with the sync again.  i'm using the 3.8.3 manifest. 

`error: Cannot checkout platform/external/autotest: GitError: Cannot initialize work tree for platform/external/autotest `

also getting  of invalid sha1 hashes and it ends with a fatal error.

**Comment by jforissier** [comment] 2020-05-30 14:30
> the 3.8.3 manifest.

???

Please post the commands you're using and I may try them here if it can help.

**Comment by zacchaeusliang** [comment] 2020-05-30 15:00
`git clone https://github.com/linaro-swg/optee_android_manifest -b 3.8.0
cd optee_android_manifest/
./sync-p-hikey960.sh`

**Comment by zacchaeusliang** [comment] 2020-05-30 15:02
formatting sorry

**Comment by jforissier** [comment] 2020-05-30 16:27
Oh, this is AOSP? OK. Let me try and I'll report back.

**Comment by zacchaeusliang** [comment] 2020-05-30 18:20
yes

**Comment by zacchaeusliang** [comment] 2020-05-30 18:20
didn't know why it closed

**Comment by jforissier** [comment] 2020-05-30 20:59
I got a similar error, not the same however:
```
error: Cannot fetch 96boards-hikey/OpenPlatformPkg.git (GitError: 96boards-hikey/OpenPlatformPkg.git update-ref: fatal: 76bbfcc0bfa4184ed5991fe89c8d7039f8ffeb46^0: not a valid SHA1
)
...
error.GitError: Cannot initialize work tree for 96boards-hikey/OpenPlatformPkg.git
```

**Comment by vchong** [comment] 2020-06-01 08:10
> git clone https://github.com/linaro-swg/optee_android_manifest -b 3.8.0

Please use `3.8.3` or `master`. In any case, `platform/external/autotest` is a repo that we never touch wrt OP-TEE development so not sure how you'd get an error for it.

> error: Cannot fetch 96boards-hikey/OpenPlatformPkg.git (GitError: 96boards-hikey/OpenPlatformPkg.git update-ref: fatal: 76bbfcc0bfa4184ed5991fe89c8d7039f8ffeb46^0: not a valid SHA1

This is fixed in [1], i.e. `3.8.3` or `master`.

[1] https://github.com/linaro-swg/optee_android_manifest/commit/5092c2b8ecabd72e99f2da2841c4a7b2c0c92cd8

**Comment by zacchaeusliang** [comment] 2020-06-01 14:34
i tried on master and it still failed

**Comment by zacchaeusliang** [comment] 2020-06-01 14:39
it has the same errors

**Comment by jforissier** [comment] 2020-06-01 16:44
@vchong I can confirm that branch `3.8.3` downloads OK here.
```
$ git clone https://github.com/linaro-swg/optee_android_manifest -b 3.8.3
$ cd optee_android_manifest/
$ ./sync-p-hikey960.sh
...
Sync done!
Please make sure there are no errors before building!
# No error message as far as I can tell
```
**Update**: build was OK too (note - Ubuntu 20.04, I had to link `gcc` and `g++` to `gcc-8` and `gcc-9` because `edk2` won't build with GCC 9).
```
$ ./build-p-hikey960.sh
...
[100% 93760/93760] Install system fs image: out/target/product/hikey960/system.img

#### build completed successfully (03:12:38 (hh:mm:ss)) ####


real	192m37.953s
user	1409m2.208s
sys	75m48.614s
Build done!
Please make sure there are no errors before flashing!
```

**Comment by vchong** [comment] 2020-06-01 17:16
@jforissier Thanks!

@zacchaeusliang Are you maybe using an existing source tree that might have become corrupted somehow instead of starting from scratch? Delete the 2 dirs below and try to sync again to see if it helps. If not, I'm out of ideas as well.

```
.repo/projects/external/autotest.git 
.repo/project-objects/platform/external/autotest.git 
```

**Comment by zacchaeusliang** [comment] 2020-06-04 04:17
i constantly try downloading and it get the same error and i have to constantly delete directories

**Comment by zacchaeusliang** [comment] 2020-06-04 04:19
it's different directories everytime

**Comment by zacchaeusliang** [comment] 2020-06-04 04:27
also now i have a problem with not a valid object error

**Comment by vchong** [comment] 2020-06-04 04:32
Sounds like you have corrupted repository metadata somewhere. You can try deleting `.repo` and run `./sync-p-hikey960.sh` again, but I don't know if that will also take a long time or not. If that doesn't work, then suggest starting from scratch again. Another thing before you continue your build, please note that this build for whatever reason (not related to OP-TEE) can't boot to the home screen. Adb works fine though.

**Comment by zacchaeusliang** [comment] 2020-06-04 04:37
which one can boot to the home screen? i need to use the UI in settings

**Comment by zacchaeusliang** [comment] 2020-06-04 05:23
and full disk encryption

**Comment by vchong** [comment] 2020-06-04 06:16
> which one can boot to the home screen? i need to use the UI in settings

You can refer to the build in https://discuss.96boards.org/t/hikey960-4gb-ram-board-aosp-optee-booting-issue although it's a bit old.

> and full disk encryption

Hardware backed or software? If hardware backed, the hikey960 build can't support it atm.

**Comment by zacchaeusliang** [comment] 2020-06-04 13:52
it's software backed since i'm intercepting the password in android's full disk encryption. Do you know which branch or manifest will support the hdmi functionality?
thanks 
zack

**Comment by vchong** [comment] 2020-06-04 15:10
Software backed is fine then. All the builds support hdmi functionality, but the hikey960 linux kernel driver is a bit off wrt to timing/frequency so it doesn't work with a lot of monitors. You can read more about it @ https://discuss.96boards.org/t/hikey960-aosp-op-tee-display-distortion-issue/9698 or similar threads (search the forum for hikey960 hdmi monitor etc).

**Comment by zacchaeusliang** [comment] 2020-06-04 15:15
>  Another thing before you continue your build, please note that this build for whatever reason (not related to OP-TEE) can't boot to the home screen. Adb works fine though.

Are you saying if i clone this repo and build it does not work? I'm just asking which one works since i'm farily new to this.

**Comment by vchong** [comment] 2020-06-04 15:20
> Are you saying if i clone this repo and build it does not work? I'm just asking which one works since i'm farily new to this.

Command line and adb should be ok for 3.8.3 or master, but has issues with going to the home screen, i.e. UI, for now. If you must have UI then please use the older build for now as referred to in https://discuss.96boards.org/t/hikey960-4gb-ram-board-aosp-optee-booting-issue.

**Comment by zacchaeusliang** [comment] 2020-06-04 15:29
so anything <3.4.2?

**Comment by vchong** [comment] 2020-06-04 15:40
> so anything <3.4.2?

Do you need to go further back? 3.4.2 is already relatively quite old. I'd just go with it since it's been verified by some of the forum users. Here we mostly run our CLI regression test suite (xtest) to make sure everything OP-TEE related runs fine and don't really mess with anything else much, so sorry but can't really tell you much about the UI, especially more so for older versions.

**Closed as completed** 2020-06-15 13:54 UTC
